# NumPy

- Biblioteca fundamental para computação numérica em Python, oferecendo estruturas de dados eficientes, como arrays multidimensionais, e operações matemáticas otimizadas.
- Operações do NumPy são muito mais eficientes do que operações baseadas em listas nativas do Python.

In [5]:
import numpy as np
import time
import matplotlib as plt

In [8]:
tamanhos = [10**i for i in range(2,9)]

tempos_nao_vetorizados = []
tempos_vetorizados = []

for tamanho in tamanhos:
    #Criar conjunto de dados
    dados = np.random.rand(tamanho)
    
    #Operação Não Vetorizada
    start_time = time.time()
    resultado_nao_vetorizado = []
    for elemento in dados:
        resultado_nao_vetorizado.append(elemento ** 2)
    tempo_nao_vetorizado = time.time() - start_time
    tempos_nao_vetorizados.append(tempo_nao_vetorizado)
    
    #Operação vetorizada
    start_time = time.time()
    resultado_vetorizado = dados ** 2
    tempo_vetorizado = time.time() - start_time
    tempos_vetorizados.append(tempo_vetorizado)

## ndarray

In [10]:
var = [1,2,3]
print(var)

var_2 = np.array([1,2,3])
print(var_2)

type(var_2)

[1, 2, 3]
[1 2 3]


numpy.ndarray

Os ndarrays possuem tipagem estática. Todos os elementos de um array precisam ter o mesmo tipo de dado.

In [11]:
vetor = [10, 3.14, "Matheus", False]
(print(type(vetor[0])))
(print(type(vetor[1])))
(print(type(vetor[2])))
(print(type(vetor[3])))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'bool'>


In [16]:
vetor_2 = np.array([10, 3.14, "Matheus", False])
print(type(vetor_2[0]))
print(type(vetor_2[1]))
print(type(vetor_2[2]))
print(type(vetor_2[3]))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


O numpy faz uma coerção automática de tipos para garantir que todos os elementos tenham o mesmo tipo.

In [17]:
print(vetor_2)

['10' '3.14' 'Matheus' 'False']


In [18]:
teste = np.array([10,15,20])

In [19]:
teste[0] + teste[1]

25

In [21]:
teste[2] = 100

In [24]:
matriz = np.array([[10,20], [30,40], [50,60]])
print(matriz)

[[10 20]
 [30 40]
 [50 60]]


In [26]:
tensor = np.array([[[10, 20], [30, 40]], [[50,60], [70, 80]], [[90, 100], [110, 120]]])
print(tensor)

[[[ 10  20]
  [ 30  40]]

 [[ 50  60]
  [ 70  80]]

 [[ 90 100]
  [110 120]]]
