# Copiando ndarrays

In [1]:
import numpy as np

In [2]:
a = ['A', 'B', 'C', 'D']
b = a
b[1] = 'X'

print(a)

['A', 'X', 'C', 'D']


In [3]:
a = np.array(['A', 'B', 'C', 'D'])
b = a
b[1] = 'X'

print(a)

['A' 'X' 'C' 'D']


Para copiar, é necessário usar uma função:

In [4]:
a = np.array(['A', 'B', 'C', 'D'])
b = a.copy()
b[1] = 'X'

print(a)

['A' 'B' 'C' 'D']


# Propriedades dos ndarray

In [6]:
vetor = np.array(['A', 'B', 'C'])

In [7]:
print("ndim: ", vetor.ndim)
print("shape: ", vetor.shape)

ndim:  1
shape:  (3,)


In [10]:
matriz = np.array([['1', '2', '3'], ['4', '5', '6']])

In [13]:
print("ndim:", matriz.ndim)
print("shape:", matriz.shape)

ndim: 2
shape: (2, 3)


In [18]:
tensor = np.array([[['A', 'B', '1'], ['C', 'D', '2']], [['E', 'F', '3'], ['G', 'H', '4']]])
print(tensor)

[[['A' 'B' '1']
  ['C' 'D' '2']]

 [['E' 'F' '3']
  ['G' 'H' '4']]]


In [19]:
print("ndim:", tensor.ndim)
print("shape:", tensor.shape) # 2 matrizes, cada uma com 2 linhas, e 3 colunas

ndim: 3
shape: (2, 2, 3)


# Reshaping de Arrays

In [22]:
a = np.array([1,2,3,4])
print(a, a.shape)

[1 2 3 4] (4,)


In [24]:
b = a.reshape((2,2))
print(b)

[[1 2]
 [3 4]]


In [27]:
c = np.array([1,2,3,4,5,6,7,8])
c = c.reshape((1,8))
print(c)

[[1 2 3 4 5 6 7 8]]


In [28]:
c = np.array([[1,2,3,4],[5,6,7,8]])
c = c.reshape((8,))
print(c)

[1 2 3 4 5 6 7 8]


In [30]:
c = c.reshape((2,2,2))
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [37]:
d = np.array([[1,2,3,4],[5,6,7,8]])
d = d.reshape((8,1))
print(d)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [40]:
d = d.T
print(d)

[[1 2 3 4 5 6 7 8]]


In [41]:
d = d.T
print(d)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


# Empilhamento

O empilhamento pode ser vertical (vstack) ou horizontal (hstack).

In [42]:
v1  = np.array(['AAA', 'BBB', 'CCC', 'DDD'])
v2 = np.array(['xxx', 'yyy', 'zzz', 'kkk'])

In [43]:
print(v1)
print(v2)

['AAA' 'BBB' 'CCC' 'DDD']
['xxx' 'yyy' 'zzz' 'kkk']


In [45]:
np.vstack([v1,v2])

array([['AAA', 'BBB', 'CCC', 'DDD'],
       ['xxx', 'yyy', 'zzz', 'kkk']], dtype='<U3')

In [46]:
np.hstack([v1,v2])

array(['AAA', 'BBB', 'CCC', 'DDD', 'xxx', 'yyy', 'zzz', 'kkk'],
      dtype='<U3')

In [49]:
c = np.vstack([v2,v1,v2])
print(c)

[['xxx' 'yyy' 'zzz' 'kkk']
 ['AAA' 'BBB' 'CCC' 'DDD']
 ['xxx' 'yyy' 'zzz' 'kkk']]


In [50]:
mat1 = [[1,2], [3,4]]
mat2 = [[100,200], [300,400]]

In [51]:
np.vstack([mat1,mat2])

array([[  1,   2],
       [  3,   4],
       [100, 200],
       [300, 400]])

In [52]:
np.hstack([mat1,mat2])

array([[  1,   2, 100, 200],
       [  3,   4, 300, 400]])