# Any, All e Múltiplas Condições

In [2]:
import numpy as np

In [8]:
mat = np.array([[1,10],[20,30]])
mat[mat>10]

array([20, 30])

Podemos fazer operações semelhantes, mas restritos a seguir "linha a linha" ou "coluna a coluna". Por exemplo, tomando como base a matriz anterior, poderíamos querer:

todas as linhas que contenham pelo menos um elemento com valor 10 ou
todas as colunas que contenham pelo menos 1 elemento abaixo do valor 10.

Para isso, usamos os métodos auxiliares any e all.

any: se qualquer elemento do meu eixo for True, retorna um valor True
all: se, e somente se, todos os elementos do meu eixo forem True, retorna True
Nas explicações, o "eixo" são as dimensões do ndarray, como discutimos algumas seções atrás.

Vamos ver alguns exemplos.

O exemplo abaixo retorna todas as linhas onde existe pelo menos um elemento com valor 10.

In [14]:
(mat==10).any(axis=1)

array([ True, False])

In [13]:
mat[(mat==10).any(axis=1)] # linhas

array([[ 1, 10]])

Por que usamos o eixo 1 nesse caso? Porque aqui, o eixo define por onde o NumPy vai "traversar" para avaliar o nosso ndarray.

O eixo 0 são as linhas. Assim, quando olhamos ao longo do eixo 0, nós estamos caminhando através das linhas. Se usássemos (mat == 10).any(axis=0), o NumPy checaria a existência de elementos iguais a 10 ao longo do eixo 0.

O processo, nesse caso, seria o seguinte:

Checaríamos se 1 == 10. Nesse caso, teríamos False.
o próximo elemento ao longo do eixo 0 (i.e., primeiro elemento da próxima linha) seria o 20. 20 == 10 também retornaria False.
Logo, nessa coluna, a resposta seria False.
Seguiríamos para a próxima coluna.
Já quando usamos (mat == 10).any(axis=1), o numpy checa ao longo do eixo 1, ou seja, ao longo das colunas. O processo fica:

checa se 1 == 10. Nesse caso, temos False.
o próximo elemento ao longo do eixo 1 (i.e., primeiro elemento da próxima coluna) seria o 10. 10 == 10 retornaria True.
Logo, nessa linha, a resposta seria True.
Seguimos para a próxima linha.
Como um outro exemplo, se quisermos trazer as colunas onde todos os elementos sejam maiores que 5, podemos usar o all. A regra de qual eixo usar permanece igual.

In [15]:
mat[:, (mat > 5).all(axis=0)] # colunas

array([[10],
       [30]])

Similar ao `and` do python, nós podemos usar múltiplas condições para filtrar dados da nossa matriz com o operador `&`.

In [16]:
mask = (mat > 10) & (mat <= 20)
mat[mask]

array([20])

No caso do `or`, nós temos o operador `|`.


In [17]:
mask = (mat == 1) | (mat >= 20)
mat[mask]

array([ 1, 20, 30])

No caso do `not`, nós temos o operador `~`.

In [18]:
mask = (mat == 1) | (mat >= 20)
mat[~mask]

array([10])

# Métodos built-in de criação de Arrays

In [19]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.zeros((2,2,5,3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [22]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [23]:
np.ones((2,3))*10

array([[10., 10., 10.],
       [10., 10., 10.]])

In [24]:
np.full((2,3), 10)

array([[10, 10, 10],
       [10, 10, 10]])

In [25]:
np_mat = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [26]:
np.full_like(np_mat, 999)

array([[999, 999, 999, 999, 999],
       [999, 999, 999, 999, 999]])

In [27]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [28]:
r1 = np.repeat(arr, 3)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

A função `np.arange` é semelhante à função `range` do Python, porém permite que peguemos valores de ponto flutuante (números com decimal) dentro do nosso intervalo.

In [ ]:
np.arange(0,11)

Outro caso comum que esbarramos para criar uma lista sequencial é quando queremos escolher uma grande quantidade de pontos entre dois números. Por exemplo, pode ser que nós queiramos fazer um mesmo cálculo para 10 valores entre 3 e 7.

Neste caso, usamos a função `np.linspace`.

Por fim, vale mencionar que o NumPy tem um sub-módulo chamado `random` (cujas funções são acessadas usando o preâmbulo `np.random`). Nele, existe um conjunto de funções focadas em gerar arrays com números aleatórios.

Por exemplo, a função `np.random.random_sample` retorna valores aleatórios entre 0 e 1.

In [30]:
np.random.random_sample((4,3))

array([[0.78034919, 0.66648126, 0.37028614],
       [0.32495852, 0.13537217, 0.86644926],
       [0.13884569, 0.29661372, 0.62859962],
       [0.55237379, 0.85947466, 0.51123526]])

In [31]:
np.random.rand(4,3)

array([[0.90462654, 0.1646352 , 0.53085665],
       [0.97664591, 0.26932876, 0.42185015],
       [0.33769538, 0.73504979, 0.7754576 ],
       [0.89617144, 0.84048131, 0.9226765 ]])