# Tipos de dados

In [1]:
import numpy as np

In [4]:
vetor = np.array([1,2,3,4,5])
vetor.dtype

dtype('int32')

In [8]:
vetor2 = np.array([1,1.2,3,4])
print(vetor2.dtype, vetor2)

float64 [1.  1.2 3.  4. ]


In [7]:
vetor3 = np.array([1,2,3,'Abacate',5])
print(vetor3.dtype, vetor3)

<U11 ['1' '2' '3' 'Abacate' '5']


In [9]:
vetor = np.array([1.3, 2.6, 3.5], dtype=np.int32)
print(vetor)

[1 2 3]


In [12]:
vetor = np.array([1,2,3,4,5], dtype = np.int32)
vetor.itemsize

4

# Conversão de dtypes de ndarrays

In [13]:
a = np.array([1.,2.,3.])
a.dtype

dtype('float64')

In [17]:
b = a.astype('int32')
print(a, b)

[1. 2. 3.] [1 2 3]


# Indexing e Slicing

In [19]:
np_mat = np.array([[1,2,3,4,5,6,7],
                  [8,9,10,11,12,13,14]])

In [20]:
np_mat[:,1]

array([2, 9])

In [21]:
np_mat[0, 2:4]

array([3, 4])

In [22]:
np_mat[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [23]:
np_mat[1,0::2]

array([ 8, 10, 12, 14])

In [24]:
np_mat[1,5] = 99
print(np_mat)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 99 14]]


In [26]:
np_mat[:,3] = 100
print(np_mat)

[[  1   2   3 100   5   6   7]
 [  8   9  10 100  12  99  14]]


In [27]:
np_mat[:,2:4] = -33
print(np_mat)

[[  1   2 -33 -33   5   6   7]
 [  8   9 -33 -33  12  99  14]]


In [28]:
np_mat = np.array([[1,2,3,4,5,6,7],
                  [8,9,10,11,12,13,14]])

In [30]:
a = np_mat[:, -4:-2]
a

array([[ 4,  5],
       [11, 12]])

# Máscara booleana e seleção avançada

In [32]:
a = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'])
a

array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'], dtype='<U1')

In [35]:
indices_de_interesse = [0,3,4,6,-1]
a[indices_de_interesse]

array(['a', 'd', 'e', 'g', 'h'], dtype='<U1')

In [61]:
a = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'])
a = a.reshape(3,3)

In [62]:
a[[0,0,2]]

array([['a', 'b', 'c'],
       ['a', 'b', 'c'],
       ['g', 'h', 'i']], dtype='<U1')

In [63]:
a[[0,0,2], [1,2,0]]

array(['b', 'c', 'g'], dtype='<U1')

In [89]:
a = np.array(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i'])

In [90]:
a[[1,4,7]]

array(['b', 'e', 'h'], dtype='<U1')

In [91]:
a[[False, True, False, False, True, False, True, True, False]]

array(['b', 'e', 'g', 'h'], dtype='<U1')

In [92]:
a == 'e'

array([False, False, False, False,  True, False, False, False, False])

In [93]:
mat = np.array([1,10,20,30]).reshape(2,2)

In [94]:
mat>=20

array([[False, False],
       [ True,  True]])

In [95]:
a[a=='f']

array(['f'], dtype='<U1')

In [96]:
a[a>'f']

array(['g', 'h', 'i'], dtype='<U1')

In [97]:
a[[True if i>=4 else False for i in range(0,len(a))]]

array(['e', 'f', 'g', 'h', 'i'], dtype='<U1')

In [98]:
np.where(a>='g')

(array([6, 7, 8], dtype=int64),)

In [99]:
np.where(mat>=10)

(array([0, 1, 1], dtype=int64), array([1, 0, 1], dtype=int64))

In [103]:
a[(a>='h') | (a<='b')]

array(['a', 'b', 'h', 'i'], dtype='<U1')

# Aritmética Básica de Ndarrays

In [104]:
vec1 = np.array([2., 4., 6., 8.])
vec2 = np.array([1., 2., 3., 4.])

In [105]:
vec1 + vec2

array([ 3.,  6.,  9., 12.])

In [106]:
vec1 - vec2 

array([1., 2., 3., 4.])

In [107]:
vec1*vec2

array([ 2.,  8., 18., 32.])

In [108]:
vec1/vec2

array([2., 2., 2., 2.])