In [14]:
import numpy as np

 Imagine que você é um cientista de dados analisando o desempenho de duas equipes de vendas ao longo de um ano. Para cada equipe, utilize um ndarray com 6 posições para representar as vendas totais ao longo de cada um dos 6 bimestres de um ano. Preencha ambos os arrays com os valores que desejar. Em seguida, calcule a média de vendas por bimestre, e indique, para cada equipe, em quais bimestres a venda média foi ultrapassada.

In [15]:
eq1 = np.array([120, 150, 200, 250, 300, 350])
eq2 = np.array([65, 78, 400, 650, 250, 85])

media_eq = (eq1+eq2)/2
print(media_eq)

print(np.where(eq1>media_eq))
print(np.where(eq2>media_eq))

[ 92.5 114.  300.  450.  275.  217.5]
(array([0, 1, 4, 5], dtype=int64),)
(array([2, 3], dtype=int64),)


Você trabalha em uma empresa e recebeu relatórios de despesas separados por trimestre. Considere 3 tipos de despesas: pessoal, insumos e diversos. Para cada tipo, use um ndarray para armazenar os 4 valores trimestrais de despesa que foram registrados ao longo do último ano. Depois disso, use ndarrays para descobrir as despesas totais de cada trimestre e, em seguida, organize todas as despesas em uma única estrutura de dados, empilhando os ndarrays.

In [16]:
pessoal = np.random.randint(10000, size = 4)
insumos = np.random.randint(10000, size = 4)
diversos = np.random.randint(10000, size = 4)

total_trimestres = pessoal + insumos + diversos

np.vstack([pessoal, insumos, diversos, total_trimestres]) 


array([[ 6780,  4101,  1496,  7845],
       [ 1038,  5681,  6745,  1974],
       [ 4335,  5282,  3002,  2716],
       [12153, 15064, 11243, 12535]])

Usand as despesas salvas em ndarrays no exercício anterior, use os ndarrays para descobrir as despesas totais de cada semestre, e não de cada trimestre.

In [18]:
total_semestres = np.array([total_trimestres[[0,1]].sum(), total_trimestres[[2,3]].sum()])
total_semestres

array([27217, 23778])

**Ex4:** Considere a seguinte matriz NumPy arr:

```
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
```

Realize as seguintes operações de slicing:

- Extraia a segunda linha da matriz arr.
- Obtenha a última coluna da matriz arr.
- Crie uma submatriz composta pelas duas primeiras linhas e pelas duas primeiras colunas de arr.
- Selecione os elementos 6, 7, 10 e 11 de arr.

In [28]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(arr[1,:])
print(arr[:,-1])
submat = arr[:2,:2]
print(submat)
print(arr[[1,1,2,2], [1,2,1,2]])
print(arr[1:, 1:3].reshape((4,)))

[5 6 7 8]
[ 4  8 12]
[[1 2]
 [5 6]]
[ 6  7 10 11]
[ 6  7 10 11]


**Ex5:** Para a mesma matriz `arr` do exercício anterior, crie uma matriz booleana com o mesmo shape de `arr` onde True representa valores maiores que 6. E depois disso, use a matriz booleana para criar um novo ndarray contendo apenas os valores maiores que 6.

In [ ]:
bool_arr = arr>6
print(bool_arr)
novo_arr = arr[bool_arr]
print(novo_arr)

[[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
[ 7  8  9 10 11 12]
